### ISSUE TITLE
No communication between ConBee2 in Docker Container

### ISSUE THREAD

**Issue by stematon** [deconz-community/deconz-docker#118]
Hi, 
I an running the deconz community container on a RasPi 4 on Raspbian 10 Buster.
After upgrading the Docker Container from 2.13 I guess to the current 2.16.01 (`docker-compose pull` command) release I had no communication between docker image and ConBee2. 
From within the container I can do GCFlasher and find the device (and for what strange reason a RaspBee that is **not** connected...)
```
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh

Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee
```
The serial number of the ConBee is not showing up. Any other attempt to communicate with the Conbee2 fails. 

I have flashed the current 26780700 firmware on Windows what worked fine. There, I could also see the serial number.
A brand new image from https://phoscon.de/en/conbee2/sdcard works. So the issue must be within the container / container configuration. 
I have followed the installation instructions from https://hub.docker.com/r/deconzcommunity/deconz

My docker-compose.yml is the following: 
``` yaml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
    - /home/pi/home-assistant:/config
    - /etc/localtime:/etc/localtime:ro
    - /media/nextcloud_hdd/homeassistant
    - /home/pi/.ssh:/root/.ssh
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: :30s
      timeout: 10s
      retries: 6

  deconz:
    container_name: deconz
    image: "deconzcommunity/deconz:latest"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/pi/.local/share/dresden-elektronik/deCONZ:/opt/deCONZ
    devices:
    - /dev/ttyACM0
    environment:
    - DECONZ_DEVICE=/dev/ttyACM0
    - DEBUG_INFO=1
    ports:
    - 8124:80
    restart: unless-stopped

  gitea:
    container_name: gitea
    image: strobi/rpi-gitea:latest
    environment:
     - USER_UID=1000
     - USER_GID=1000
    restart: unless-stopped
    volumes:
    - /media/nextcloud_hdd/gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    #privileged: true
    ports:
    - "3000:3000"
    - "222:22"

```
I am also in contact with dresden-elektronik, they are trying their best but I guess we are at some point where they will say hardware is fine - not our business what would be fair 

What else could I do to get the ConBee running? 
Where / how can I see the logfiles? As `journalctl` seems to be disabled I am a bit confused where to look for the logs...
And, a bit off-topic, how can I edit text files? I have never ever seen a linux without vi...

Best regards, Stefan
