### ISSUE TITLE
deCONZ cannot connect to Conbee II on Raspi 4

### ISSUE THREAD

**Issue by FWinkler79** [deconz-community/deconz-docker#129]
Hi there, 

and thanks for providing this image!
I recently switched to your version coming from the deprecated predecessor image you mention on your main page.
Attached to my Raspi 4, I am running a Conbee II. Unfortunately, deCONZ won't connect to Conbee II.
It seems to detect it, since it shows it on the Login screen, but once logged in, no devices are found, and in the upper right corner it displays a 172.x.x.x address and under _Gateway_ > _Firmware_ says "not connected".

I already updated the Conbee II stick to the latest firmware version from May 2022, and that went fine.
Still, no connection with the latest image version (2.17.01), and also not with the previous one (2.17.00)

This is my docker-compose.yml:

```yaml
version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0  # Conbee device path
    environment:
      - TZ=Europe/Brussels
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1
      - DEBUG_HTTP=1
      - DECONZ_DEVICE=/dev/ttyACM0 # Conbee device path
      - DECONZ_START_VERBOSE=1
```

What could be the issue here? And how could I debug that?

Thanks!

**Comment by FWinkler79** [comment]
It turns out, `privileged: true` does that trick, i.e. running the container in privileged mode like so:

```yaml
version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    privileged: true    # <--- This is important, since otherwise deCONZ won't connect to Conbee II on Raspi 4. 
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=Europe/Brussels
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1
      - DEBUG_HTTP=1
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_START_VERBOSE=1
```

This could be mentioned somewhere in the instructions.
