### ISSUE TITLE
Cant get this working

### ISSUE THREAD

**Issue by glassbox-sco** [deconz-community/deconz-docker#135]
Im having trouble setting this up, ive put your repository into the docker in unraid and changed the other bit to /opt/deConz for the container port but its not working. When i start the docker, and goto the webui it starts up but nothing shows in the settings page for the conbee 2.
Is it possible to show some screen shots of where everything goes exactly.
Also could we get this integration in the apps section of unraid as Spaceinvaderone doesnt seem to be updating this now.

**Comment by senilio** [comment]
/opt/deConz is not the correct mount point, try /opt/deCONZ

Second, supplying an up to date Unraid app is well out of scope of this project. If you want to run this container in Unraid, I recommend using the Compose Manager plugin, which allows you to run containers using docker-compose.

Here is a working example of a config running under Unraid, with a static IP set:

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz-community
    restart: always
    volumes:
      - /mnt/cache/appdata/deconzcommunity:/opt/deCONZ/
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1234567-if00:/dev/ttyACM0
    ports:
      - 80:80
      - 443:443
      - 6080:6080
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
    networks:
      br0:
        ipv4_address: 192.168.12.8
networks:
  br0:
    external: true
```

Not that indentation matters. Adjust the relevant bits like device path and ip-address.
