### ISSUE TITLE
Docker container failed to reconnect network

### ISSUE THREAD

**Issue by b23prodtm** [deconz-community/deconz-docker#151]
```
 raspbee-deconz-hue  [deconzcommunity/deconz] Starting deCONZ...
 raspbee-deconz-hue  [deconzcommunity/deconz] Current deCONZ version: 2.19.01
 raspbee-deconz-hue  [deconzcommunity/deconz] Web UI port: 8080
 raspbee-deconz-hue  [deconzcommunity/deconz] Websockets port: 443
 raspbee-deconz-hue  [deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=8080 --ws-port=443
 raspbee-deconz-hue  [deconzcommunity/deconz] Modifying user and group ID
 raspbee-deconz-hue  [deconzcommunity/deconz] Starting deCONZ...
 raspbee-deconz-hue  [deconzcommunity/deconz] Current deCONZ version: 2.19.01
 raspbee-deconz-hue  [deconzcommunity/deconz] Web UI port: 8080
 raspbee-deconz-hue  [deconzcommunity/deconz] Websockets port: 443
 raspbee-deconz-hue  [deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=8080 --ws-port=443
 raspbee-deconz-hue  [deconzcommunity/deconz] Modifying user and group ID
 raspbee-deconz-hue  [deconzcommunity/deconz] Checking device group ID
 raspbee-deconz-hue  [deconzcommunity/deconz] VNC Disabled
 raspbee-deconz-hue  QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
 raspbee-deconz-hue  libpng warning: iCCP: known incorrect sRGB profile
 raspbee-deconz-hue  This plugin does not support propagateSizeHints()
 raspbee-deconz-hue  This plugin does not support propagateSizeHints()
 raspbee-deconz-hue  22:21:05:033 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
 raspbee-deconz-hue  22:21:05:080 /opt/deCONZ/config.ini exists and is writeable
 raspbee-deconz-hue  22:21:05:080 /opt/deCONZ/zll.db exists and is writeable
 raspbee-deconz-hue  22:21:05:428 dev /dev/ttyAMA0
 raspbee-deconz-hue  22:21:05:428 dev /dev/ttyS0
 raspbee-deconz-hue  22:21:05:428 COM: /dev/ttyS0 / serialno: , RaspBee
 raspbee-deconz-hue  22:21:05:429 ZCLDB init file /opt/deCONZ/zcldb.txt
 raspbee-deconz-hue  22:21:06:421 DDF enabled for Gold status
 raspbee-deconz-hue  22:21:07:474 gw run mode: normal
 raspbee-deconz-hue  22:21:07:474 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
 raspbee-deconz-hue  22:21:07:474 sd-card cid: 125678415354430020ffffffff01265b
 raspbee-deconz-hue  22:21:07:531 DB sqlite version 3.34.1
 raspbee-deconz-hue  22:21:07:543 DB PRAGMA page_count: 46
 raspbee-deconz-hue  22:21:07:543 DB PRAGMA page_size: 4096
 raspbee-deconz-hue  22:21:07:543 DB PRAGMA freelist_count: 0
 raspbee-deconz-hue  22:21:07:543 DB file size 188416 bytes, free pages 0
 raspbee-deconz-hue  22:21:07:543 DB PRAGMA user_version: 9
 raspbee-deconz-hue  22:21:07:543 DB cleanup
 raspbee-deconz-hue  22:21:07:549 DB create temporary views
 raspbee-deconz-hue  22:21:07:948 [INFO] - Timezone read is 'Etc/UTC'
 raspbee-deconz-hue  22:21:07:948 [INFO] - Setting environment variable 'TZ=:/etc/localtime'...
 raspbee-deconz-hue  22:21:07:962 Started websocket server on 0.0.0.0, port: 443
 raspbee-deconz-hue  22:21:07:984 [INFO] - Found file containing button maps. Parsing data...
 raspbee-deconz-hue  22:21:08:050 [INFO] - Button maps loaded.
 raspbee-deconz-hue  22:21:08:060 found node plugin: libde_rest_plugin.so - REST API Plugin
 raspbee-deconz-hue  22:21:08:068 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
 raspbee-deconz-hue  22:21:08:113 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
 raspbee-deconz-hue  22:21:08:225 dlg action: Read binding table
 raspbee-deconz-hue  22:21:09:189 dev /dev/ttyAMA0
 raspbee-deconz-hue  22:21:09:189 dev /dev/ttyS0
 raspbee-deconz-hue  22:21:09:189 COM: /dev/ttyS0 / serialno: , RaspBee
 raspbee-deconz-hue  22:21:13:483 Announced to internet https://phoscon.de/discover
 raspbee-deconz-hue  22:21:13:483 discovery server date: Sun, 30 Oct 2022 22:21:13 GMT
 raspbee-deconz-hue  22:21:13:483        local time seems to be ok
 raspbee-deconz-hue  22:21:14:201 Skip idle timer callback, too early: elapsed 909 msec
 raspbee-deconz-hue  22:21:16:201 DEV Tick.Init: booted after 8000 seconds
 raspbee-deconz-hue  22:21:29:202 start reconnect to network
 raspbee-deconz-hue  22:21:34:201 try to reconnect to network try=1
 raspbee-deconz-hue  22:21:39:201 try to reconnect to network try=2
 raspbee-deconz-hue  22:21:44:201 try to reconnect to network try=3
 raspbee-deconz-hue  22:21:49:201 try to reconnect to network try=4
 raspbee-deconz-hue  22:21:51:269 New websocket 192.168.1.20:52680 (state: 3) 
```
[homebridge.log.txt](https://github.com/deconz-community/deconz-docker/files/9896977/homebridge.log.txt)

I'm making a docker gateway and homebridge.io to connect to zigbee light bulbs and ikea tradfri cupboards lights..
[Plugin Raspbee II device in RaspberryPI 3B](https://phoscon.de/en/raspbee2)

```
version: '2'
services:
  raspbee-deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - deconz:/opt/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    volumes:
      - homebridge:/homebridge
volumes:
  homebridge:
  deconz:
```

**Comment by phdelodder** [comment]
You would need to provide more logging

**Comment by JoopKok** [comment]
I have the same issue, which started when watchtower autoupdated the deconz docker package unattended. (Oops, that should not go unattended).

It looks like there is a bug in the package, not allowing the container to correctly connect to the Raspbee II. Easily solved by going back to image: image: deconzcommunity/deconz:2.18.02

As far as logging goes, the snipped shared by b23prodtm is all there is to share. Maybe the /dev/ttyAMA0 mapping is broken?

**Comment by phdelodder** [comment]
Then it should be reported in https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by jo-me** [comment]
same thing here. Conbee I is not recognized in the latest version.. 

Maybe you should take it down..

**Comment by phdelodder** [comment]
I have tested on my test and prod (conbee1 and conbee2) and have no issues. So you need to provide more information. 

Can you see in the container has the needed device?

**Comment by Mimiix** [comment]
> Then it should be reported in https://github.com/dresden-elektronik/deconz-rest-plugin

No issues have been reported in our repo yet.

**Comment by Mimiix** [comment]
> I have the same issue, which started when watchtower autoupdated the deconz docker package unattended. (Oops, that should not go unattended).
> 
> It looks like there is a bug in the package, not allowing the container to correctly connect to the Raspbee II. Easily solved by going back to _image: deconzcommunity/deconz:2.18.02_
> 
> As far as logging goes, the snipped shared by b23prodtm is all there is to share. Maybe the /dev/ttyAMA0 mapping is broken?

Do the logs say anything related to reason?

**Comment by wmn79** [comment]
Same issue here, rolling back to 2.18.02 solves it again. 
I have attached the log file and had set DEBUG_DEV=1 (not sure if that is helpful or needed). [deconzlog.txt](https://github.com/deconz-community/deconz-docker/files/9863629/deconzlog.txt)

This line (shows up twice) seems to be the issue:
 `stat: cannot statx '/dev/ttyUSB-Conbee': No such file or directory afterwards `
Afterwards it only shows: `dev /dev/ttyAMA0`

Any suggestions or things I can try?

**Comment by wmn79** [comment]
Ok I have seem to resolve it by directly setting the device to: /dev/ttyUSB1 instead of to my sym-link: /dev/ttyUSB-Conbee. Then all seems to work again.

As I have two USB devices I really like to use the symlink as it is mapped on the serial of the stick. Otherwise when I do a reboot the ttyUSB1 can become the P1-cable instead and then I have to change the docker-compose for both deconz and DSMR on every reboot.

**Comment by phdelodder** [comment]
@wmn79 for a conbee2 I have following device config in my docker:
```
devices:
  - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2220342-if00:/dev/ttyACM0
```

**Comment by wmn79** [comment]
thanks @phdelodder

There is still something I don't understand:

When I put this in my docker compose it works:

```
    devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KGOE-if00-port0:/dev/ttyUSB1
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB1
```
If I put this or only use the part under devices and remove the deconz_device in environment (as it says ttyUSB0 is default) it doesn't work:
```
    devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KGOE-if00-port0:/dev/ttyUSB0
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB0
```

Can you explain why this last option doesn't work? In my understanding the first part of device before the : is the actual device and the part after the : is how you want to map it in the docker. Or is that not correct and does it work differently?

**Comment by phdelodder** [comment]
@wmn79 Could you provide me the logs with `DECONZ_START_VERBOSE=1` added as environment variable?

**Comment by wmn79** [comment]
Off course!

The **not working** config:
 ```
   devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KGOE-if00-port0:/dev/ttyUSB0
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB0
```
[ttyUSB0log.txt](https://github.com/deconz-community/deconz-docker/files/9869393/ttyUSB0log.txt)

The **working** config:
```
   devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KGOE-if00-port0:/dev/ttyUSB1
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB1
```
[ttyUSB1log.txt](https://github.com/deconz-community/deconz-docker/files/9869398/ttyUSB1log.txt)

And my full docker compose file: 
```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KGOE-if00-port0:/dev/ttyUSB1
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB1
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_DDF=0
      - DEBUG_DEV=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=xxxxxxx
      - TZ=Europe/Amsterdam
```

**Comment by Mimiix** [comment]
@phdelodder So for you it works as expected?

**Comment by Mimiix** [comment]
Additionally:

What is working?

Conbee? Conbee 2? Raspbee? Raspbee 2?

I know there has been a change in the driver thingys for Raspbee.

**Comment by Mimiix** [comment]
Not sure why. I asked Manup to check in.

But if it works, i am not sure what happened. @Others here: What are you using?

**Comment by phdelodder** [comment]
@Mimiix For me it works as expected

**Comment by b23prodtm** [comment]
As of the /dev/ directory I also found the /dev/ttyS0 which works as serial device for Raspbee , but let's see how it works now it's 2.18 still trying to reconnect and I'll try the image with latest tag

**Comment by JoopKok** [comment]
I found time to check upon my issue, which appeared to be an user error. I used the snippeted on the frontpage to configure my RASPBEE II:

`version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true                # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyACM0                # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
      - DECONZ_START_VERBOSE=0`

This appeared to be wrong on my part: I noticed that my USB P1 cable on my PI3 (not related to deconz) stopped working. First thing I did is remove the:

`privileged: true                # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.`

to stop the container from being able to mount the /dev/usb1 device. That clearly worked, then I noticed that:

`
    devices: 
      - /dev/ttyACM0                # This is the USB device that Conbee II is running on.
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
`

is wrong in my case. I changed this to:
`
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0     

    environment:
      - DECONZ_DEVICE=/dev/ttyAMA0
`

In short: a configuration change and removing priviledged mode fixed my issue.

**Comment by b23prodtm** [comment]
> I'm making a docker gateway and homebridge.io to connect to zigbee light bulbs and ikea tradfri cupboards lights.. [Plugin Raspbee II device in RaspberryPI 3B](https://phoscon.de/en/raspbee2)
> 
> ```
> version: '2'
> services:
>   raspbee-deconz:
>     image: deconzcommunity/deconz
>     container_name: deconz
>     restart: always
>     privileged: true
>     ports:
>       - 8080:8080
>       - 443:443
>     volumes:
>       - deconz:/opt/deCONZ
>     devices:
>       - /dev/ttyAMA0
>     environment:
>       - DECONZ_WEB_PORT=8080
>       - DECONZ_WS_PORT=443
>       - DEBUG_INFO=1
>       - DEBUG_APS=0
>       - DEBUG_ZCL=0
>       - DEBUG_ZDP=0
>       - DEBUG_OTA=0
>   homebridge:
>     image: oznu/homebridge:latest
>     restart: always
>     network_mode: host
>     ports:
>       - 8581:8581
>     logging:
>       driver: json-file
>       options:
>         max-size: "10mb"
>         max-file: "1"
>     volumes:
>       - homebridge:/homebridge
> volumes:
>   homebridge:
>   deconz:
> ```

I switched to [Home Assistant Container version}(https://www.home-assistant.io/installation/raspberrypi) and add-on from [Zigbee Mosquito](https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html) 
Raspbee II (GPIO card) is in 
```
version: '2'
services:
  homeassistant:
    container_name: hass
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - config:/config
      - localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyS0
      - /dev/AMA0
  
  homebridge:
    container_name: hb
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    volumes:
      - homebridge:/homebridge
volumes:
  homebridge:
  config:
  localtime:
  ```
 in use and detected
from HomeAssistant integrated add-on without any further configuration
