### ISSUE TITLE
Only pairing new devices if I unplug and replug it

### ISSUE THREAD

**Issue by dferrandizmont** [deconz-community/deconz-docker#170]
Hello, I'm not sure if this is a bug or what but I'm facing this problem almost since I changed from [marthoc](https://github.com/marthoc/docker-deconz) to this docker container. 

When I try to add a new device I must unplug the `Conbee II` and replug it in order to discover the new decive, otherwise, even the logs say `send permit join, duration: 65` it doesn't add any and once I do it, discovers the device in just a few seconds. Is this the correct behavior or I'm missing something?

This is my docker-compose file

``` YAML
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz-conbee
    network_mode: host
    restart: always
    ports: 
      - XXXXX:80
      - XXXXX:443
    volumes:
      - /deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=XXXXX
      - DECONZ_WS_PORT=XXXXX
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=XXX
      - DECONZ_VNC_PASSWORD=XXXXXXXXXXXXX
      - DECONZ_NOVNC_PORT=XXXX
```

Thanks.
