### ISSUE TITLE
Access ConBee via /dev/serial/by-id

### ISSUE THREAD

**Issue by Gerrit-KMeier** [deconz-community/deconz-docker#171]
It's quite common that USB serial adapter tend to change their address when plugin in a different order or into another USB-Port. Normally one can cirmuvent it by using the softlink `/dev/serial/by-id/` which has a pointer to the real USB-Port /dev/ttyXXXX.

### Available USB2Serial Devices in my system
In this example the last entry is the right one. The rest can and should be ignored to the deconz container.

```
notroot@thindocker:~/deconz$ ls /dev/serial/by-id/ -ls
total 0
0 lrwxrwxrwx 1 root dialout 13 Jan 21 15:22 usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0 -> ../../ttyUSB0
0 lrwxrwxrwx 1 root dialout 13 Jan 21 15:22 usb-busware.de_CUL868-if00 -> ../../ttyACM0
0 lrwxrwxrwx 1 root dialout 13 Jan 21 15:22 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2147763-if00 -> ../../ttyACM1

```

### What I did yo far:
Both /dev/ttyACMx Sticks struggle with the address assignment on startup of the computer. They **do** receive an address all the time, but these addresses **may** swap on startup of the host.

I altered the docker-compose.yaml like this:

```yaml
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports:
      - 8888:8888
      - 8001:8001
    volumes:
      - ./opt/deCONZ:/opt/deCONZ
      - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - /dev/ttyACM0
      - /dev/ttyACM1
    environment:
      - DECONZ_WEB_PORT=8888
      - DECONZ_WS_PORT=8001
      - DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2147763-if00
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Berlin
      - DECONZ_UPNP=1
      - DECONZ_VNC_MODE=0
      - DECONZ_START_VERBOSE=1
```

I passed both ACM Devices so the system has the opportunity to choose the right one, accordning to the softlink in `/dev/serial/by-id/` folder

I noticed these lines in the logfile upon start.
```
17:04:17:272 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:17:312 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:18:735 failed to reconnect to network try=7
17:04:21:280 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:21:324 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:22:277 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:22:329 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:23:735 failed to reconnect to network try=8
17:04:24:794 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:26:310 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:26:354 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:27:289 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:27:340 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
17:04:28:736 failed to reconnect to network try=9
17:04:31:280 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
```

So the process is not concerned about the address given.

### Environmental Variables
I snatched these these variables from the console within the container `docker exec -it deconz /bin/bash`

```
root@4f26bcb13152:/# set
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:expand_aliases:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=([0]="0")
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="1" [2]="4" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='5.1.4(1)-release'
COLUMNS=282
DEBIAN_FRONTEND=noninteractive
DEBUG_APS=0
DEBUG_DDF=0
DEBUG_DEV=0
DEBUG_ERROR=0
DEBUG_HTTP=0
DEBUG_INFO=1
DEBUG_OTA=0
DEBUG_OTAU=0
DEBUG_ZCL=0
DEBUG_ZDP=0
DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2147763-if00
DECONZ_GID=1000
DECONZ_NOVNC_PORT=6080
DECONZ_START_VERBOSE=1
DECONZ_UID=1000
DECONZ_UPNP=1
DECONZ_VERSION=2.20.00
DECONZ_VNC_DISPLAY=0
DECONZ_VNC_MODE=0
DECONZ_VNC_PASSWORD=changeme
DECONZ_VNC_PASSWORD_FILE=0
DECONZ_VNC_PORT=5900
DECONZ_WEB_PORT=8888
DECONZ_WS_PORT=8001
DIRSTACK=()
EUID=0
GROUPS=()
HISTFILE=/root/.bash_history
HISTFILESIZE=500
HISTSIZE=500
HOME=/root
HOSTNAME=4f26bcb13152
HOSTTYPE=x86_64
IFS=$' \t\n'
LINES=86
MACHTYPE=x86_64-pc-linux-gnu
MAILCHECK=60
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIPESTATUS=([0]="1")
PPID=0
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
PS2='> '
PS4='+ '
PWD=/
SHELL=/bin/bash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=1
TERM=xterm
TZ=Europe/Berlin
UID=0

```

So what's going on?

**Comment by senilio** [comment]
Your config is slightly messy, just use the following:

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports:
      - 8888:8888
      - 8001:8001
    volumes:
      - ./opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2147763-if00:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=8888
      - DECONZ_WS_PORT=8001
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Berlin
      - DECONZ_UPNP=1
      - DECONZ_VNC_MODE=0
      - DECONZ_START_VERBOSE=1
```
