### ISSUE TITLE
Container Exited On System Reboot

### ISSUE THREAD

**Issue by AlexKusnezov** [deconz-community/deconz-docker#192]
Hey guys,

everytime I reboot my system the deconz container is reported as ```exited```
I have to manulally edit the port to something elese and then back in order to get it working again.
here's my config:
```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_UPNP=0
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - TZ=Europe/Berlin
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=dsfsffa
```

Hope you can help me out.
