### ISSUE TITLE
Firmware not connected

### ISSUE THREAD

**Issue by tebbbb** [deconz-community/deconz-docker#209]
Hi,

i am using a RPI4B with Ubuntu on it. I changed the interface in the docker-compose to AMA0 and when i start, this is what i get:

14:35:38:181 discovery server date: Sun, 08 Oct 2023 14:35:38 GMT
14:35:38:181 	 local time seems to be ok
14:35:40:519 DEV Tick.Init: booted after 8000 seconds
14:35:48:595 dev /dev/ttyAMA0
14:35:53:019 start reconnect to network
14:35:58:269 failed to reconnect to network try=1
14:36:02:604 dev /dev/ttyAMA0
14:36:03:518 failed to reconnect to network try=2
14:36:08:518 try to reconnect to network try=3

and it says Firmware Not connected in the UI

**Comment by senilio** [comment]
What device do you have?

Paste full compose file

**Comment by tebbbb** [comment]
Raspberry Pi 4B

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
```

**Comment by tebbbb** [comment]
How do i set this variable with using docker-compose? docker-compose up -d -e DECONZ_DEVICE=/dev/ttyAMA0 ?
How can i check if the host OS recognized the Raspbee?

**Comment by phdelodder** [comment]
```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_DEVICE=/dev/ttyAMA0
      ````
