### ISSUE TITLE
Changing HTTPS ports does not work?

### ISSUE THREAD

**Issue by antgustech** [deconz-community/deconz-docker#215]
Been using this image for a year with the following dockerfile without any issues:

```
`
version: "3.8"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: unless-stopped
    privileged: true
    ports: 
      - 81:81
      - 443:443
      - 5900:5900
      - 6080:6080 
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0 #Must be USB port where Conbee II stick is inserted
    environment:
      - TZ=Europe/Stockholm
      - DECONZ_WEB_PORT=81
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=0
`
```

However, now I needed the 443 port for another container and I'm trying to figure out how. According to docs it should be enough to set the port mapping and the environment variable DECONZ_WS_PORT and so I did but when I do, the the lights stop working. If I change it back to 443 they start working again. https://github.com/deconz-community/deconz-docker

      - 444:444
      - DECONZ_WS_PORT=444

Any advice on how to change from 443?
