### ISSUE TITLE
2.24.2 docker image not working in rootless mode on Ubuntu 22.04 host

### ISSUE THREAD

**Issue by troed** [deconz-community/deconz-docker#220]
Downgrading to 2.24.0 works fine. I did not test 2.24.1

The issue presents as the following in the log:

```
+ exec gosu deconz /usr/bin/deCONZ --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=2 --dbg-aps=2 --dbg-zcl=2 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=2 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=8380 --ws-port=8381 -platform minimal
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
QThread::start: Thread creation error (Operation not permitted)
QThread::start: Thread creation error (Operation not permitted)

```

**Comment by senilio** [comment]
Could you share your docker-compose file, and hopefully we'll be able to reproduce the error?

**Comment by troed** [comment]
Sorry, sure. I did try looking into the actual reason (which could be Qt libs or seccomp problems) but didn't manage to find anything. The host is fully updated, on kernel 5.15.0-88 and uses cgroup2.

```
version: '3'

networks:
  external_network:
  internal_network:
    internal: true

services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    volumes:
      - /home/hass/deconz/storage:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=8380
      - DECONZ_WS_PORT=8381
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_DISPLAY=1
      - DECONZ_VNC_PORT=5901
      - DECONZ_VNC_PASSWORD=something
    networks:
      - internal_network
      - external_network
    ports:
      - "8180:80"
      - "8543:443"
      - "8380:8380"
      - "8381:8381"
      - "5901:5901"

```

(other containers removed)
