### ISSUE TITLE
Failed to reconnect to network

### ISSUE THREAD

**Issue by DanielKlt** [deconz-community/deconz-docker#248]
I have the deconz docker image deployed on a K8s cluster and having the following issue that I cannot connect to the web interface of the deployment. 
I am getting an http response code of ```HTTP ERROR 431```. Any ideas on how to solve this?
While checking the log, it says that the connection to the network failed.

Pod-logs:
```
18:57:18:662 failed to reconnect to network try=1 
18:57:23:912 failed to reconnect to network try=2
18:57:28:912 failed to reconnect to network try=3
18:57:33:912 failed to reconnect to network try=4
18:57:38:912 failed to reconnect to network try=5
18:57:43:912 failed to reconnect to network try=6
18:57:48:912 failed to reconnect to network try=7
18:57:53:912 failed to reconnect to network try=8
18:57:58:912 failed to reconnect to network try=9
18:58:03:912 failed to reconnect to network try=10
18:58:08:912 reconnect network failed, try later
```

K8s Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deconz-deployment
  labels:
    app: deconz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deconz
  template:
    metadata:
      labels:
        app: deconz
    spec:
      containers:
        - name: deconz
          image: deconzcommunity/deconz
          ports:
            - containerPort: 8124
            - containerPort: 443
          env:
            - name: TZ
              value: "Europe/Brussels"
            - name: DECONZ_WEB_PORT
              value: "8124"
            - name: DECONZ_WS_PORT
              value: "443"
            - name: DEBUG_INFO
              value: "1"
            - name: DEBUG_APS
              value: "0"
            - name: DEBUG_ZCL
              value: "0"
            - name: DEBUG_ZDP
              value: "0"
            - name: DEBUG_OTAU
              value: "0"
            - name: DEBUG_HTTP
              value: "0"
            - name: DECONZ_DEVICE
              value: "/dev/ttyUSB.DECONZ"
            - name: DECONZ_VNC_MODE
              value: "1"
            - name: DECONZ_VNC_PORT
              value: "5900"
            - name: DECONZ_VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deconz-secret
                  key: DECONZ_VNC_PASSWORD
            - name: DECONZ_VNC_MODE
            - name: DECONZ_UID
              value: "1000"
            - name: DECONZ_GID
              value: "1000"
            - name: DECONZ_START_VERBOSE
              value: "0"
            - name: DECONZ_BAUDRATE
              value: "115200"
          volumeMounts:
            - name: deconz-vol
              mountPath: /data/deconz
            - name: ttyusb
              mountPath: /dev/ttyUSB.DECONZ
      volumes:
        - name: deconz-vol
          hostPath:
            path: /data/deconz
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB.DECONZ
```

I also have created a udev rule, that mappes the deconz conbee II on ```/dev/ttyUSB.DECONZ```
