### ISSUE TITLE
ConBee 2 Stick is not visible on the Phoscon start page

### ISSUE THREAD

**Issue by T3CHN3W** [deconz-community/deconz-docker#254]
Hello, I use a Raspi4 and Docker for the installation and use of the Conbee 2 stick.
For the installation I took the Docker-compose file and modified it for my requirements:

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 8085:8085
      - 443:443
    volumes:
      - /volume1/docker/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=8085
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

```
I put this in the stack area and deployed it. 
The start page is accessible via the ports without any problems and I can see the start logo on the page, but the ConBee 2 stick is not displayed.

I connected to it via SSH and checked the following things:

Is the stick detected by the Pi?
```
>>lsubs

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1cf1:0030 Dresden Elektronik ZigBee gateway [ConBee II]
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Has the kernel identified the USB drive?
```
>>cd /dev
>>ls

--> I see the ttyACM0 serial
```

Second check:
```
/dev/serial/by-id# ls -al /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2444549-if00
lrwxrwxrwx 1 
root root 13 Jul  6 11:16 /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2444549-if00 -> ../../ttyACM0
```

Since the Pi now lists the stick under ttyACM0, it should be possible to see the stick on the Phoscon start page, shouldn't it?

I hope you can help me here?

Many thanks in advance!

**Comment by T3CHN3W** [comment]
I was able to solve the problem with a simple additional command line. I found it in a Home Assistant forum post: [Link](https://community.home-assistant.io/t/troubleshooting-configuring-conbee-stick-ii-in-home-assistant-docker-with-zha/307061/3)

The problem was solved with the following line:
```
privileged: true
```

My docker compose looks now like this:

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 8085:8085
      - 443:443
    volumes:
      - /volume1/docker/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=8085
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
     privileged: true
```
