### ISSUE TITLE
BootLoop when VNC turned on

### ISSUE THREAD

**Issue by ocsi01** [deconz-community/deconz-docker#269]
I know this issue was discussed before, but I don't seem to find the solution. #184  #161

Running docker on a clean Ubuntu 24.04 setup. Creating the deconz-docker container via docker compose:
```
##########################################
#                deConz                  #
########################################## 

  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.178.103
    ports:
      - 80:80
      - 443:443
      - 5902:5902
      - 6082:6082
    volumes:
      - /mnt/Container/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5902
      - DECONZ_VNC_DISPLAY=0
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_NOVNC_PORT=6082
      - DECONZ_START_VERBOSE=1
```

As you see, I tried many things, changing ports.
`DECONZ_VNC_MODE=0` container starts and works properly. `DECONZ_VNC_MODE=1` container errors and restarts.
most relecant part of the logs:
```

[deconzcommunity/deconz] Modifying user and group ID
+ echo [deconzcommunity/deconz] Modifying user and group ID
+ [ 1000 != 1000 ]
+ [ 1000 != 1000 ]
+ echo [deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] Checking device group ID
      
+ [ 0 != 0 ]
+ [ -e /dev/ttyUSB0 ]
+ [ -e /dev/ttyACM0 ]
+ DEVICE=/dev/ttyACM0
+ [ -e /dev/ttyAMA0 ]
+ [ -e /dev/ttyS0 ]
+ stat --printf=%g /dev/ttyACM0
+ DIALOUTGROUPID=20
+ DIALOUTGROUPID=20
+ [ 20 != 20 ]
+ stat -c %A /dev/ttyACM0
      
+ cut -c 5-7
+ GROUPPERMISSIONS=rw-
+ [ rw- = --- ]
      
+ [ 1 != 0 ]
+ [ 5902 -lt 5900 ]
+ DECONZ_VNC_DISPLAY=:2
+ echo [deconzcommunity/deconz] VNC port: 5902
[deconzcommunity/deconz] VNC port: 5902
+ [ ! -e /opt/deCONZ/vnc ]
+ ln -sfT /opt/deCONZ/vnc /home/deconz/.vnc
+ chown deconz:deconz /home/deconz/.vnc
+ chown deconz:deconz /opt/deCONZ -R
+ echo [deconzcommunity/deconz] VNC DISABLE PASSWORD: 0
[deconzcommunity/deconz] VNC DISABLE PASSWORD: 0
+ [ 0 = 0 ]
      
+ [ 0 != 0 ]
+ echo changeme
+ tigervncpasswd -f
+ chmod 600 /opt/deCONZ/vnc/passwd
+ chown deconz:deconz /opt/deCONZ/vnc/passwd
+ SECURITYTYPES=VncAuth,TLSVnc
+ tigervncserver -version
      
+ [ 0 != 0 ]
+ gosu deconz tigervncserver -kill :*
tigervncserver: No VNC server running for this user!
+ gosu deconz tigervncserver -list :* -cleanstale
TigerVNC server sessions:
X DISPLAY #	RFB PORT #	RFB UNIX PATH	PROCESS ID #	SERVER
+ [ -e /tmp/.X2-lock ]
+ continue
+ [ -e /tmp/.X11-unix/X2 ]
+ continue
+ gosu deconz tigervncserver -SecurityTypes VncAuth,TLSVnc :2
You will require a password to access your desktops.
getpassword error: Inappropriate ioctl for device
+ export DISPLAY=:2
+ [ 6080 = 0 ]
+ [ 6080 -lt 6080 ]
+ NOVNC_CERT=/opt/deCONZ/vnc/novnc.pem
+ [ -f /opt/deCONZ/vnc/novnc.pem ]
+ openssl x509 -noout -in /opt/deCONZ/vnc/novnc.pem -checkend 0
      
+ [ 0 != 0 ]
+ [ ! -f /opt/deCONZ/vnc/novnc.pem ]
+ chown deconz:deconz /opt/deCONZ/vnc/novnc.pem
+ gosu deconz websockify -D --web=/usr/share/novnc/ --cert=/opt/deCONZ/vnc/novnc.pem 6080 localhost:5902
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /usr/share/novnc
  - SSL/TLS support
  - Backgrounding (daemon)
Password:[deconzcommunity/deconz] NOVNC port: 6080
+ echo [deconzcommunity/deconz] NOVNC port: 6080
      
+ [ 0 != 0 ]
      
+ [ 1 != 1 ]
+ mkdir -p /opt/deCONZ/otau
+ ln -sfT /opt/deCONZ/otau /home/deconz/otau
+ chown deconz:deconz /home/deconz/otau
+ chown deconz:deconz /opt/deCONZ -R
+ exec gosu deconz /usr/bin/deCONZ --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --dev-test-managed=0 --http-port=80 --ws-port=443
qt.qpa.xcb: could not connect to display :2
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

What's odd, is it looks like some ENV variables are not pick up, while others do.  ` VNC port: 5902` is correct but `DECONZ_VNC_DISPLAY=:2` and `NOVNC port: 6080` and `DECONZ_VNC_PASSWORD` looks unset.

**Comment by ocsi01** [comment]
Emptyinh `/mnt/Container/deconz` made `NOVNC port: 6082` to pick up, but still getting `DECONZ_VNC_DISPLAY=:2` and `getpassword error: Inappropriate ioctl for device` suggests password is also not set.

Also /opt/deCONZ/vnc/passwd does not exist.

**Comment by mattreim** [comment]
First try to enter a password for “changeme”.
`DECONZ_VNC_PASSWORD=changeme`

**Comment by phdelodder** [comment]
Could you try to add privileged: true to you compose? Just wondering if it's not enough permissions

**Comment by ocsi01** [comment]
`privileged: true` Does not make a difference.
However `DECONZ_VNC_DISABLE_PASSWORD=1` does. When I set this, the container is booting and after some wonky retries, I've managed to login, load my backup and get my old system up and running. ( I can login to VNC web via port 6080)

So the issue is, how to make this work with VNC Password?

**Comment by phdelodder** [comment]
I have managed to reproduce it and I'll see what can be done

**Comment by phdelodder** [comment]
When setting `NON_ROOT=1`  it doesn't work, so it's a rights issue that needs to be resolved. Can you try adding `NON_ROOT=0` to the environment options?

**Comment by ocsi01** [comment]
This gives me the same error:
```
##########################################
#                deConz                  #
########################################## 

  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5900:5900
      - 6080:6080
    volumes:
      - /mnt/Container/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - NON_ROOT=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
#      - DECONZ_VNC_DISABLE_PASSWORD=1
      - DECONZ_VNC_PASSWORD=mypass
      - DECONZ_NOVNC_PORT=6080
      - DECONZ_START_VERBOSE=1
```

**Comment by phdelodder** [comment]
Can you test the new dev build? https://github.com/deconz-community/deconz-docker/pkgs/container/deconz-docker/291855448?tag=dev

**Comment by ocsi01** [comment]
Unfortunately no difference:
```
##########################################
#                deConz                  #
########################################## 

  deconz:
    image: deconzcommunity/deconz:dev
    container_name: deconz
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5900:5900
      - 6080:6080
    volumes:
      - /mnt/Container/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
#      - NON_ROOT=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
#      - DECONZ_VNC_DISABLE_PASSWORD=1
      - DECONZ_VNC_PASSWORD=mypass
      - DECONZ_NOVNC_PORT=6080
      - DECONZ_START_VERBOSE=1
```

Also tried it with ` - NON_ROOT=0`. Same error. With `- DECONZ_VNC_DISABLE_PASSWORD=1` still works.

**Comment by phdelodder** [comment]
Could you please retest the dev image?

**Comment by ocsi01** [comment]
Dev looks good now, thanks!
```

##########################################
#                deConz                  #
########################################## 

  deconz:
    image: deconzcommunity/deconz:dev
    container_name: deconz
    privileged: true
    restart: always
    networks:
      my-macvlan-network: 
        ipv4_address: 192.168.178.102
    ports:
      - 80:80
      - 443:443
      - 5900:5900
      - 6080:6080
    volumes:
      - /mnt/Container/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
#      - NON_ROOT=0
      - DEBUG_OTA=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
#      - DECONZ_VNC_DISABLE_PASSWORD=1
      - DECONZ_VNC_PASSWORD=mypass
      - DECONZ_NOVNC_PORT=6080
      - DECONZ_START_VERBOSE=1
```
