### ISSUE TITLE
ConBee II does not connect any devices after reinstallation

### ISSUE THREAD

**Issue by T3CHN3W** [deconz-community/deconz-docker#273]
Deconz runs in a Docker container on my Raspi Pi 4B (4GB).
Recently I switched from the SD card boot to a pure SSD boot from the USB3 slot.

When reinstalling Deconz again (in Docker) and connecting my devices (3x Aqara Temp./Humidty sensors and 1 x Sonoff Plug (Type: S26R22BTPF)) only the 3 Humidity sensors could be connected without any problems. I could only connect the Sonoff Plug by trying several times via the "Intermediate plug" (previously you had to connect the power plug via lights).
The Sonoff Plug worked for 1 day and then could no longer be controlled via Homebridge. Even if the plug was switched on and off manually, the status in the Deconz app (and Homebridge) did not change.

Since I could not reconnect the plug via "Intermediate plug" or "Lights", I have now set up the entire Docker container again and deleted the Deconz folder from the SSD beforehand for a clean installation. 

The container starts without any problems and I see the gateway and can connect to it (CONBEE 2). 

Unfortunately, I can now connect neither the AQARA sensors nor the Sonoff plug.
Does anyone have an idea where I could start troubleshooting here?

Product: ConBee II
Gateway Version: 2.28.1
Firmware: 26720700

_Log-File_
```
[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.28.1
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --dev-test-managed=0 --http-port=80 --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

_Portainer File:_
```
version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    ports:
      - 8085:80
      - 443:443
    volumes:
      - /volumeDocker/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyACM0 # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyACM0 # This is the USB device that Conbee II is running on.
      - DECONZ_START_VERBOSE=0
```
