### ISSUE TITLE
Synology woes

### ISSUE THREAD

**Issue by turbo2ltr** [deconz-community/deconz-docker#286]
My system was working running HA and Phoscon in docker containers on my Synology. The problem was my Phoscon and Conbee II firmware were from 2021 (I'm a firm believer of don't fix what aint broke for this exact reason).

I was finding that the support for certain  zigbee device types was missing (like measuring power with 3rd Reality plugs) so I braved an upgrade.  I had to go back into the repo since the upgrade instructions were removed from the readme a while ago, but I followed those.

I originally ran the old container with 
```
 docker run -p 8080:80 -p 6080:6080 -p 5900:59000 -p 20443:443 --name deconz --privileged --device=/dev/ttyACM0:/dev/ttyACM0 marthoc/deconz latest
```

For this container I created a new stack (I use Portainer) and pointed it to the original volume on the old container.
```
services:
  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz2
    privileged: true
    network_mode: "bridge"
    ports:
      - "8080:80"
      - "6080:6080"
      - "5900:59000"
      - "20443:443"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - DECONZ_UID=0
      - DECONZ_GID=0
      - DECONZ_DEVICE=/dev/ttyACM0
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTA=1
    volumes:
      - /volume1/@docker/volumes/eaee760434bb37356fb5ffa9ea048e476fdab158103a195ef152d834b52fd509/_data:/opt/deCONZ
```

It boots up and aside from ALL my sensors changing names which broke everything in HA,  Phoscon just can't find the dongle.  This just repeats:
```
13:44:23:325 failed to reconnect to network try=1
13:44:23:979 COM: /dev/ttyACM0 / serialno: , ConBee II
```
I tried the latest dongle firmware as well as several older version (even though the newest firmware is still only from 2022)

The `/dev/ttyACM0` device is present inside the container with R/W access and disappears if I unplug it so the passthrough seems to be working. (I'm still on DSM 6)

Are there any other troubleshooting steps I might be able to take as I'm at a loss at this point.

Startup log attached.

[_deconz2_logs.txt](https://github.com/user-attachments/files/20123075/_deconz2_logs.txt)
