### ISSUE TITLE
Compatibility with user namespaces

### ISSUE THREAD

**Issue by p4PpS** [deconz-community/deconz-docker#51]
Hello all,

I am using docker with [user namespaces](https://docs.docker.com/engine/security/userns-remap/).

For this to work with deconz, I need to disable the user namespace for the deconz container (--userns=host, resp. userns_mode: "host"). Otherwise, all mounted devices are mounted as nobody:nogroup instead of root:dialout. With the container from marthoc this still worked.

With the new container from deconz-community this does not work anymore, because "sudo" is used when building the container. Unfortunately, ["sudo" cannot be used](https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container) if user namespaces are generally enabled and disabled for this particular container.

Does anyone have a useful tip for me how to migrate from marthoc to deconz-community without disabling user namespaces in general?

<details>
    <summary>My docker-compose file</summary>

```
﻿﻿version: '3.8'
services:
  deconz:
    image: deconzcommunity/deconz:2.13.03
    container_name: deconz
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyS0
    environment:
      - TZ="Europe/Brussels"
      - DECONZ_WEB_PORT=8081
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyS0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_UID=1000
      - DECONZ_GID=1000
      - DECONZ_START_VERBOSE=0
    userns_mode: "host" # Since /dev/tty* will otherwise be mounted as nobody:nogroup instead of root:dialout
    labels:
      - traefik.enable=true
      - traefik.http.routers.deconz.rule=Host(`deconz.example.com`)
      - traefik.http.routers.deconz.entrypoints=websecure
      - traefik.http.services.deconz.loadbalancer.server.port=8081
```

</details>

Thanks in advance!
