### ISSUE TITLE
No new devices detected

### ISSUE THREAD

**Issue by mario-fliegner** [deconz-community/deconz-docker#56]
Hi all,

I'm running deCONZ on a RPI3 using `docker-compose`. Before, I was running on the `marthoc/deconz` image, so I did the migration. After starting the `deconzcommunity/deconz` on the `latest` tag, I'm able to access the Phoscon app again and all my sensors showing up again (I only use deCONZ to connect my XIAOMI temperature sensors, nothing else). If I display the properties of one sensor, it has a current timestamp for *Refreshed* and also the temperature/humidity changes in the App. For me, this looks fine. So, the deCONZ USB stick on my RPI3 gets somehow routed into the Docker container. Otherwise, I would guess, the timestamp as well as all other props would not be updated.
But the issue I'm facing is, that I cant get another XIAOMI temperature sensor connected. I ran into the problem because 3 sensors where running out of power (empty battery). After changing the batteries, the App states *Not Reachable* for all 3. I did also try to delete one of it and to add it as a new one again, but the search doesn't find it anymore. Now, this looks like there is an issue with mapping the USB stick to the container? However, I've tried both for devices mapping:  `/dev/ttyACM0:/dev/ttyACM0` as well as just ` '/dev/ttyACM0`, no success. As I haven't moved the deCONZ stick to another USB port on my RPI3, I assume this is still correct. And for the existing sensors it's still working. 
Any thoughts on what went wrong or what I can try?

This is my current `docker-compose.yml`:
```
version: "3.7"
services:
  deconz:
      build:
        context: ./images/deconz
      container_name: smarthome_deconz_latest
      network_mode: host
      restart: always
      volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/opt/smarthome/deconz:/opt/deCONZ'
      devices:
        - '/dev/ttyACM0:/dev/ttyACM0'
      env_file:
        - 'deconz.env'
```

Content of Dockerfile  in `./images/deconz` - just 2 lines of code:

```
# docker pull deconzcommunity/deconz:latest
FROM deconzcommunity/deconz:latest

LABEL maintainer="Mario Fliegner"
```

Content of `deconz.env`:
```
DECONZ_WEB_PORT=8085
DEBUG_INFO=1
DEBUG_APS=0
DEBUG_ZCL=0
DEBUG_ZDP=0
DEBUG_OTAU=0
TZ=Europe/Berlin
```

Command to start:
`/opt/smarthome/docker-compose/docker-compose.yml up --build`

Log file: [logDECONZ.log](https://github.com/deconz-community/deconz-docker/files/7739640/logDECONZ.log)

Some screenshots:
![image](https://user-images.githubusercontent.com/58735999/146648845-bb11cc8c-ceed-404c-9752-24c46f46c6c7.png)
![image](https://user-images.githubusercontent.com/58735999/146648874-12f28e23-9623-4340-978e-a8becd77415d.png)

This is the content of the mapped folder on my RPI3. I'm wondering about the `session.default` as it contains all sensors (even the deleted one). Is this file still used? Or can it be deleted? The both folders `otau` and `devices` where created with the new image, however, both are empty. 
![image](https://user-images.githubusercontent.com/58735999/146649406-b6754070-b1c9-4635-b82b-52eb6b0bd758.png)

**Comment by phdelodder** [comment]
Could you share you log? With DECONZ_START_VERBOSE=1 added to the environment parameters?.

**Comment by mario-fliegner** [comment]
This is the output of with the requested parameter: [deCONZ_verbose.log](https://github.com/deconz-community/deconz-docker/files/7739915/deCONZ_verbose.log)

**Comment by phdelodder** [comment]
Could you specify DECONZ_DEVICE=/dev/ttyACM0 in the compose file under environment parameters?

**Comment by mario-fliegner** [comment]
Did it, however, no success. To double-check whether the CONBEE stick will be recognized at all, I've unplugged it from the PI and restarted. After restarting, I was not able anymore to login to the Phoscon app. Plugged in again and I was able to login. For me, it's another proove that the mapping basically works (somehow...). Here's the log after a fresh start having `DECONZ_DEVICE=/dev/ttyACM0` specified in the environment parameter: 
[conbee_log.log](https://github.com/deconz-community/deconz-docker/files/7756750/conbee_log.log).
I've also tried specifying `privileged: true` for the container, no success. Are there any other logs or loglevels that can shed a light on it?

**Comment by mario-fliegner** [comment]
Please find attached an updated log. I've tried to connect a new sensor (for which I've changed the battery) and I also tried to connect one of the remaining (existing + working) ones in the App again. Please look at line 947 (`17:25:56:191 send permit join, duration: 65`), where I tried to add the one where I've changed the battery (in line 1038 it states `17:37:06:483 Search sensors done`). And starting in line 1043 I was trying to search for one of the existing sensors.
[conbee_log.log](https://github.com/deconz-community/deconz-docker/files/7756844/conbee_log.log)

**Comment by phdelodder** [comment]
@manup would you have idea?

**Comment by manup** [comment]
Is the /dev/ttyACM0 listed on the host system, and all prior contains stopped which were accessing the device?



I think the **cgroup** approach might help to mitigate device name woes, unfortunately the issues from the marthoc/deconz repository aren't available anymore, there was a description for it.

Here is what my `docker-compose.yml` looks like:

```
version: "2.3"
services: 
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
#    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
    device_cgroup_rules:
      - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
      - 'c 188:* rmw' # allow creation of /dev/ttyUSBx nodes via mknod
    devices:
      - /dev/bus/usb

    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_ERROR=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```

This allows the creation of USB device names inside the container if they are missing.
