### ISSUE TITLE
Can't detect lights

### ISSUE THREAD

**Issue by Ombrelin** [deconz-community/deconz-docker#61]
Hello,

I'm running the container on a raspberry PI 4, with the following docker-compse : 

```yml
 deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 8080:80
    volumes:
      - /home/arsene/deconz:/opt/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_START_VERBOSE=1
```

None of my 3 Phillips Hue light will show up when pairing them.
When I used the Conbee and Dezcon on my desktop PC, the lights are detected an I can interacted with them, but in the container I get no light detected.

Any clue about this ?Thank you in advance

**Comment by senilio** [comment]
If you are unable to detect lights, I think you're in the wrong repo :) I think you were looking for https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by Ombrelin** [comment]
I understand but my lights are detected when I used the desktop version, so I rather think that my issue comes from my docker setup

**Comment by senilio** [comment]
Can you submit some debug logs?

Set DEBUG_APS=1 and DEBUG_INFO=1 , restart the container and try pairing a device. Share the logs and we'll take a look.

Thanks

**Comment by phdelodder** [comment]
Please add DECONZ_DEVICE to your environment parameters and if that still doesn't work please provide a log.

**Comment by Ombrelin** [comment]
Thank you for your help, here is the log :
[logs.txt](https://github.com/deconz-community/deconz-docker/files/7788591/logs.txt)

**Comment by phdelodder** [comment]
Could you please specify DECONZ_DEVICE ?

**Comment by Ombrelin** [comment]
I have, the logs have been produced with the following docker-compose : 

```yml
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 8080:80
    volumes:
      - /home/arsene/deconz:/opt/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_START_VERBOSE=1
      - DECONZ_DEVICE=/dev/ttyACM0
```
