### ISSUE TITLE
Can't start VNC

### ISSUE THREAD

**Issue by AngeloDellaMorte** [deconz-community/deconz-docker#64]
Hello,
I cant't start this Container with vnc enabled.
I Get the following error:
<img width="954" alt="Screenshot 2021-12-29 at 23 53 13" src="https://user-images.githubusercontent.com/24492422/147709108-ee8464db-c777-4f38-b1b4-499bab6a43d2.png">

Don't know what todo. With old Container VNC was working.

**Comment by andysaab** [comment]
It`s same for me too.

**Comment by senilio** [comment]
@AngeloDellaMorte can you share your docker-compose.yml please?

**Comment by senilio** [comment]
The interesting part from your screenshot is the fact that it can't get the hostname of the machine, aka the container itself.

**Comment by Gloomyeye** [comment]
Hello, I have the same problem now with the latest commit. This is my docker-compose:
  deconz:
     container_name: deconz
     image: deconzcommunity/deconz:stable
     network_mode: host
     restart: always
     hostname: deconz
     volumes:
       - /home/pi/deconz:/opt/deCONZ
     devices:
       - /dev/ttyACM0
     environment:
       - TZ=${TZ}
       - DECONZ_WEB_PORT=${DECONZ_WEB_PORT} #80
       - DECONZ_WS_PORT=${DECONZ_WS_PORT} #443
       - DEBUG_INFO=1
       - DEBUG_APS=0
       - DEBUG_ZCL=0
       - DEBUG_ZDP=0
       - DEBUG_OTAU=0
       #- UDEV=1 #For latest/stable
       - DECONZ_VNC_MODE=1
       - DECONZ_VNC_PORT=${DECONZ_VNC_PORT} #5900
       - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
     labels:
       - "com.centurylinklabs.watchtower.enable=true"

**Comment by andysaab** [comment]
> The interesting part from your screenshot is the fact that it can't get the hostname of the machine, aka the container itself.
![image](https://user-images.githubusercontent.com/56047524/147734512-38ae7567-827e-4a48-ba87-1c3d61e92da2.png)
It`s  my container settings

**Comment by AngeloDellaMorte** [comment]
I'm using docker tool from my synoloy nas so don't have compose. But here are my settings:
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "DECONZ_VERSION=2.13.04",
                "DECONZ_WEB_PORT=80",
                "DECONZ_WS_PORT=443",
                "DEBUG_INFO=1",
                "DEBUG_APS=0",
                "DEBUG_ZCL=0",
                "DEBUG_ZDP=0",
                "DEBUG_OTAU=0",
                "DEBUG_ERROR=0",
                "DECONZ_DEVICE=/dev/ttyACM0",
                "DECONZ_VNC_MODE=0",
                "DECONZ_VNC_DISPLAY=0",
                "DECONZ_VNC_PASSWORD=secret",
                "DECONZ_VNC_PASSWORD_FILE=0",
                "DECONZ_VNC_PORT=5901",
                "DECONZ_NOVNC_PORT=6081",
                "DECONZ_UPNP=1",
                "DECONZ_UID=1000",
                "DECONZ_GID=1000",
                "DECONZ_START_VERBOSE=0"
            ],

And it is running in Host mode.

**Comment by andysaab** [comment]
Guys! All of us have this issue on Synology docker or some have it on other system?

**Comment by eifinger** [comment]
I have the same problem running on rpb3. My docker-compose.yaml is the following:

```yaml
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:2.13.04
    container_name: deconz
    restart: unless-stopped
    ports:
      - "5900:5900"
      - "8081:8081"
      - "8444:8444"
    volumes:
      - /home/pi/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_VNC_PASSWORD=<secret>
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=1
      - DECONZ_WEB_PORT=8081
      - DECONZ_WS_PORT=8444
```

Tag 2.13.03 works fine

**Comment by Gloomyeye** [comment]
I run the deconz docker container on a rpi4b with raspian pi os lite. However, I haven't installed the bullseye version yet.

**Comment by andysaab** [comment]
Tnx, guys! Now is working perfect with VNC!

**Comment by AngeloDellaMorte** [comment]
It's also working for me! THX!

**Comment by phdelodder** [comment]
I have created a "dev" image: `deconzcommunity/deconz:development` could you please try with this image and give me the log of `/home/deconz/.vnc/raspberrypi:5900.log`

You either map `/home/deconz` as a volume or use `docker cp container_name:/home/deconz/.vnc/raspberrypi:5900.log /localpath/`

**Comment by antgustech** [comment]
Not sure if related. This is my docker-compose file:

`version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:2.13.04
    container_name: deconz
    restart: always
    ports: 
      - 81:81
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=81
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=1`
Installed VNC viewer and I go to 192.x.x.x:5900 but I cannot connect.

**Comment by phdelodder** [comment]
@antgustech you need to expose the VNC port in the ports config

**Comment by donnib** [comment]
For me it's not working no matter which version i try to use, what is weird is that the log indicates the password is not set when i clearly set it in the docker-compose file..

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:2.13.04
    container_name: deconz
    restart: always
    volumes:
      - /var/docker_data/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0    
    ports:
      - "5910:5910"      
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Copenhagen
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=deconz
      - DECONZ_VNC_PORT=5910
      - DECONZ_START_VERBOSE=0      
````
Here is the log 
```
2022-01-18T09:03:31.357530478Z [deconzcommunity/deconz] Starting deCONZ...
2022-01-18T09:03:31.357568852Z [deconzcommunity/deconz] Current deCONZ version: 2.13.04
2022-01-18T09:03:31.357585191Z [deconzcommunity/deconz] Web UI port: 80
2022-01-18T09:03:31.357607697Z [deconzcommunity/deconz] Websockets port: 443
2022-01-18T09:03:31.357629937Z [deconzcommunity/deconz] Modifying user and group ID
2022-01-18T09:03:31.357644370Z [deconzcommunity/deconz] Checking device group ID
2022-01-18T09:03:31.364337954Z [deconzcommunity/deconz] VNC port: 5910
2022-01-18T09:03:31.627051740Z
2022-01-18T09:03:31.627094573Z You will require a password to access your desktops.
2022-01-18T09:03:31.627108346Z
2022-01-18T09:03:31.633948158Z getpassword error: Inappropriate ioctl for device
2022-01-18T09:03:31.934413173Z WebSocket server settings:
2022-01-18T09:03:31.934740493Z   - Listen on :6080
2022-01-18T09:03:31.934767514Z   - Flash security policy server
2022-01-18T09:03:31.935131296Z   - Web server. Web root: /usr/share/novnc
2022-01-18T09:03:31.935160405Z   - SSL/TLS support
2022-01-18T09:03:31.935234533Z   - Backgrounding (daemon)
2022-01-18T09:03:31.937193986Z Password:[deconzcommunity/deconz] NOVNC port: 6080
2022-01-18T09:03:31.989431619Z qt.qpa.screen: QXcbConnection: Could not connect to display :10
2022-01-18T09:03:31.989570754Z Could not connect to any X display.
```

@phdelodder  Any ideas ?
