### ISSUE TITLE
WebUI is not listening on configured port

### ISSUE THREAD

**Issue by Moyal1** [deconz-community/deconz-docker#72]
I'm running the deconz container with the environment variable "DECONZ_WEB_PORT=8124"
When the docker starts it says "Web UI port: 8124" but then it listens on port 8080 instead of 8124

> [deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.13.04
[deconzcommunity/deconz] Web UI port: 8124
[deconzcommunity/deconz] Websockets port: 8125
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
19:48:21:370 Invalid app argument --dbg-ota=
19:48:21:400 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/

**Comment by phdelodder** [comment]
I have pushed an hour ago a fix for this.

**Comment by Moyal1** [comment]
It didn't fix it

**Comment by phdelodder** [comment]
Could you please provide me with a debug log?

**Comment by Didier3L** [comment]
Bonjour 
j'ai exactement le même problème

```
services:
     deconz:
         image: deconzcommunity/deconz:latest
         container_name: deconz-community
         privileged: false
         restart: always
         networks:
             default:
                 ipv4_address: 192.168.1.245
         volumes:
           - /volume1/docker/deconz-community:/opt/deCONZ
         devices:
           - "/dev/ttyACM1:/dev/ttyACM1"
         environment:
           - PUID=1032
           - PGID=101
           - DECONZ_WEB_PORT=80
           - DECONZ_WS_PORT=443
           - DEBUG_INFO=1
           - DEBUG_APS=0
           - DEBUG_ZCL=0
           - DEBUG_ZDP=0
           - DEBUG_OTAU=0
           - DECONZ_VNC_MODE=1
           - DECONZ_VNC_PORT=5900
           - DECONZ_NOVNC_PORT=6080
           - DECONZ_DEVICE=/dev/ttyACM1
           - DECONZ_VNC_PASSWORD=password
           - TZ=Europe/Paris

```
le service démarre sur 192.168.1.245:8080 
Port Socket : 8088
![image](https://user-images.githubusercontent.com/23530136/147883070-355dbb04-c644-487c-aaf2-55950bd886b3.png)
