### ISSUE TITLE
Running deconz:stable - presented with "A new version is available. The update needs to be installed manually via Docker."

### ISSUE THREAD

**Issue by kompiz** [deconz-community/deconz-docker#75]
What the title says - I'm running stable, the web gui says I'm on version 2.13.04 / 18/12/2021. Checking the [changelog ](https://phoscon.de/en/changelog/) page, this version isn't listed, and is after the latest one on there. 

I'm on firmware 26580700.

My docker-compose.yml looks like so:
```
version: "2"
services:
  deconz:
    network_mode: host
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
 ```
