### ISSUE TITLE
deconz container crashes on startup

### ISSUE THREAD

**Issue by zigurana** [deconz-community/deconz-docker#86]
Trying to use deconz-docker  using a ConBee II stick put into a Synology 220+ NAS running DSM 7.0.

After manually loading the usb modules, USB device seems to be recognized all right.
Device firmware was succesfully updated on a win10 machine to version 26720700 

Container is defined using docker-compose:
```
  deconz:
    profiles:
      - WIP
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: 'no'
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/deconz:/opt/deCONZ
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=9080
      - DECONZ_WS_PORT=4443
      - DECONZ_START_VERBOSE=1
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_ÙID=0
      - DECONZ_GID=0
      - TZ=${TZ}
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```

Container crashes within seconds though, failing an assert on db.
```
deconz           | DDF:  MANY MANY LINES OF DDF logging
deconz           | 22:15:24:986 DDF: loaded resource item descriptor: config/temperature
deconz           | 22:15:24:986 DDF: loaded resource item descriptor: state/consumption
deconz           | 22:15:24:986 DDF: loaded resource item descriptor: state/lastupdated
deconz           | 22:15:24:994 gw run mode: docker
deconz           | 22:15:24:994 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
deconz           | 22:15:24:994 Started websocket server on 0.0.0.0, port: 4443
deconz           | 22:15:24:995 create default username and password
deconz           | 22:15:24:995 [INFO] - Found file containing button maps. Parsing data...
deconz           | 22:15:24:000 [INFO] - Button maps loaded.
deconz           | 22:15:24:000 found node plugin: libde_rest_plugin.so - REST API Plugin
deconz           | 22:15:24:001 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
deconz           | 22:15:25:005 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
deconz           | 22:15:25:025 dlg action: Read binding table
deconz           | 22:15:26:041 COM: /dev/ttyACM0 / serialno: DE2487051, ConBee II
deconz           | 22:15:26:901 Skip idle timer callback, too early: elapsed 949 msec
deconz           | This plugin does not support propagateSizeHints()
deconz           | 22:15:27:869 Device firmware version 0x26720700 ConBee II
deconz           | 22:15:27:878 unlocked max nodes: 512
deconz           | 22:15:27:973 Device protocol version: 0x010E
deconz           | 22:15:27:985 new node - ext: 0x00212effff080f3a, nwk: 0x0000
deconz           | 22:15:28:039 Current channel 15
deconz           | 22:15:28:060 CTRL ANT_CTRL 0x03
deconz           | 22:15:28:061 CTRL ZDP_RESPONSE handler 0x0000
deconz           | 22:15:28:094 Device protocol version: 0x010E
deconz           | 22:15:28:176 CTRL ANT_CTRL 0x03
deconz           | 22:15:28:186 CTRL ZDP_RESPONSE handler 0x0000
deconz           | 22:15:28:801 Skip idle timer callback, too early: elapsed 933 msec
deconz           | deCONZ: ../../../../deconz/src/plugins/de_web/database.cpp:6685: int DB_GetSubDeviceItemCount(QLatin1String): Assertion `db' failed.
deconz exited with code 139
```

At first, the restart policy was set to `unless-stopped`, which caused me to miss this assertion failure entirely.
(At first I was getting errors on 'failed open com status', but those seems to have been replaced by this).
But because the web interface is accessable  before the 'reboot', I've been able to play around in the UI, setting the main PW mostly.
I've never been able to succesfully link with a switch or light when running this docker yet (it works on Win10 though). 
 
From the looks of it, this is the same issue as #77, but for me dropping the container and recreating it did not solve the issue.

Any tips are greatly appreciated.
